public final class kotlinx.coroutines.flow.LintKt$retry$1 extends kotlin.coroutines.jvm.internal.SuspendLambda implements kotlin.jvm.functions.Function2
{
    int label;

    public void <init>(kotlin.coroutines.Continuation)
    {
        kotlinx.coroutines.flow.LintKt$retry$1 r0;
        kotlin.coroutines.Continuation $r1;

        r0 := @this: kotlinx.coroutines.flow.LintKt$retry$1;

        $r1 := @parameter0: kotlin.coroutines.Continuation;

        specialinvoke r0.<kotlin.coroutines.jvm.internal.SuspendLambda: void <init>(int,kotlin.coroutines.Continuation)>(2, $r1);

        return;
    }

    public final kotlin.coroutines.Continuation create(java.lang.Object, kotlin.coroutines.Continuation)
    {
        kotlinx.coroutines.flow.LintKt$retry$1 r0;
        kotlin.coroutines.Continuation $r1;
        java.lang.Object $r2;

        r0 := @this: kotlinx.coroutines.flow.LintKt$retry$1;

        $r2 := @parameter0: java.lang.Object;

        $r1 := @parameter1: kotlin.coroutines.Continuation;

        r0 = new kotlinx.coroutines.flow.LintKt$retry$1;

        specialinvoke r0.<kotlinx.coroutines.flow.LintKt$retry$1: void <init>(kotlin.coroutines.Continuation)>($r1);

        $r1 = (kotlin.coroutines.Continuation) r0;

        return $r1;
    }

    public volatile java.lang.Object invoke(java.lang.Object, java.lang.Object)
    {
        kotlinx.coroutines.flow.LintKt$retry$1 r0;
        java.lang.Object $r1, $r2;
        java.lang.Throwable $r3;
        kotlin.coroutines.Continuation $r4;

        r0 := @this: kotlinx.coroutines.flow.LintKt$retry$1;

        $r1 := @parameter0: java.lang.Object;

        $r2 := @parameter1: java.lang.Object;

        $r3 = (java.lang.Throwable) $r1;

        $r4 = (kotlin.coroutines.Continuation) $r2;

        $r1 = virtualinvoke r0.<kotlinx.coroutines.flow.LintKt$retry$1: java.lang.Object invoke(java.lang.Throwable,kotlin.coroutines.Continuation)>($r3, $r4);

        return $r1;
    }

    public final java.lang.Object invoke(java.lang.Throwable, kotlin.coroutines.Continuation)
    {
        kotlinx.coroutines.flow.LintKt$retry$1 r0;
        java.lang.Throwable $r1;
        kotlin.coroutines.Continuation $r2;
        kotlin.Unit $r3;
        java.lang.Object $r4;

        r0 := @this: kotlinx.coroutines.flow.LintKt$retry$1;

        $r1 := @parameter0: java.lang.Throwable;

        $r2 := @parameter1: kotlin.coroutines.Continuation;

        $r2 = virtualinvoke r0.<kotlinx.coroutines.flow.LintKt$retry$1: kotlin.coroutines.Continuation create(java.lang.Object,kotlin.coroutines.Continuation)>($r1, $r2);

        r0 = (kotlinx.coroutines.flow.LintKt$retry$1) $r2;

        $r3 = <kotlin.Unit: kotlin.Unit INSTANCE>;

        $r4 = virtualinvoke r0.<kotlinx.coroutines.flow.LintKt$retry$1: java.lang.Object invokeSuspend(java.lang.Object)>($r3);

        return $r4;
    }

    public final java.lang.Object invokeSuspend(java.lang.Object)
    {
        kotlinx.coroutines.flow.LintKt$retry$1 r0;
        java.lang.Boolean $r1;
        java.lang.Object $r2;
        int $i0;
        java.lang.IllegalStateException $r3;

        r0 := @this: kotlinx.coroutines.flow.LintKt$retry$1;

        $r2 := @parameter0: java.lang.Object;

        staticinvoke <kotlin.coroutines.intrinsics.IntrinsicsKt: java.lang.Object getCOROUTINE_SUSPENDED()>();

        $i0 = r0.<kotlinx.coroutines.flow.LintKt$retry$1: int label>;

        if $i0 != 0 goto label1;

        staticinvoke <kotlin.ResultKt: void throwOnFailure(java.lang.Object)>($r2);

        $r1 = staticinvoke <kotlin.coroutines.jvm.internal.Boxing: java.lang.Boolean boxBoolean(boolean)>(1);

        return $r1;

     label1:
        $r3 = new java.lang.IllegalStateException;

        specialinvoke $r3.<java.lang.IllegalStateException: void <init>(java.lang.String)>("call to \'resume\' before \'invoke\' with coroutine");

        throw $r3;
    }
}
